FROM nginx:1.21-alpine

# Удаляем дефолтную конфигурацию Nginx
RUN rm /etc/nginx/conf.d/default.conf

# Копируем нашу конфигурацию
COPY nginx.conf /etc/nginx/conf.d/

# Создаем директории для статики
RUN mkdir -p /usr/share/nginx/static /usr/share/nginx/media

EXPOSE 80