# Generated by Django 5.2.4 on 2025-08-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_alter_order_address_alter_order_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Фамилия'),
        ),
    ]
