# Generated by Django 5.2.4 on 2025-09-02 18:07

from django.db import migrations


def fill_orderitem_prices(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')

    order_items = OrderItem.objects.filter(product__isnull=False).iterator(chunk_size=1000)
    items_to_update = []
    for order_item in order_items:
        order_item.price = order_item.product.price
        items_to_update.append(order_item)
    if items_to_update:
        OrderItem.objects.bulk_update(items_to_update, ['price'], batch_size=1000)


def reverse_fill_prices(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    OrderItem.objects.all().update(price=0)


class Migration(migrations.Migration):
    dependencies = [
        ('foodcartapp', '0042_orderitem_price_alter_orderitem_order_and_more'),
    ]
    operations = [
        migrations.RunPython(fill_orderitem_prices, reverse_fill_prices),
    ]
