# Generated by Django 5.2.4 on 2025-09-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_auto_20250902_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unprocessed', 'Необработанный'), ('underway', 'В работе'), ('delivery', 'Доставка'), ('completed', 'Завершен')], db_index=True, default='unprocessed', max_length=20, verbose_name='Статус'),
        ),
    ]
