# Generated by Django 5.2.4 on 2025-09-07 08:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_order_comments_alter_order_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='called_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='дата и время прозвона'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='дата и время доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='registated_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='дата и время регистрации'),
        ),
    ]
