# Generated by Django 5.2.4 on 2025-09-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_order_called_at_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличностью'), ('electronic', 'Электронно')], db_index=True, default='Необработанный', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
