# Generated by Django 5.2.4 on 2025-09-11 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_restaurant_lat_restaurant_lon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='registated_at',
            new_name='registered_at',
        ),
    ]
